version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  frontend:
    type: boolean
    default: false
  backend:
    type: boolean
    default: false

jobs:
  trigger-workflows:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/cirlcleci_trigger.sh && .circleci/cirlcleci_trigger.sh

  build-frontend:
    docker:
      - image: circleci/node:12.14.0

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Public
          command: yarn workspace frontend deploy
      - persist_to_workspace:
          root: ./frontend
          paths:
            - out

  deploy-frontend:
    docker:
      - image: circleci/node:12.14.0

    steps:
      - checkout

      - attach_workspace:
          at: ./frontend

      - run:
          name: install netlify cli
          command: sudo npm install netlify-cli -g
      - run:
          name: Netlify Deploy
          command: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=./frontend/out -p

  deploy-backend:
    machine: true

    working_directory: ~/project

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "33:0c:30:05:8a:6d:4c:22:5c:2a:da:90:b6:56:d6:15"
      - run:
          name: Add Dokku to known_hosts
          command: ssh-keyscan -H 178.128.86.161 >> ~/.ssh/known_hosts
      - run:
          name: Build Docker image
          command: cd backend &&  docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$HUB_PASSWORD" | docker login $HOST_REGISTRY -u "$HUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: "Deploy app to Digital Ocean Server via Docker"
          command: |
            ssh root@178.128.86.161 "docker pull $IMAGE_NAME:latest && docker tag $IMAGE_NAME:latest dokku/revhere-api:latest && dokku tags:deploy revhere-api latest"

workflows:
  version: 2
  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  frontend:
    when: << pipeline.parameters.frontend >>
    jobs:
      - build-frontend
      - deploy-frontend:
          filters:
            branches:
              only:
                - master
          requires:
            - build-frontend

  backend:
    when: << pipeline.parameters.backend >>
    jobs:
      - deploy-backend:
          filters:
            branches:
              only:
                - master
  # build-and-deploy:
  #   jobs:
  #     - build
  #     - deploy-prod:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #         requires:
  #           - build
