version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  deploy-prod:
    machine: true
    # docker:
    #   - image: circleci/node:12.14.0
    steps:
      - checkout

      # - setup_remote_docker
      - run:
          name: "Login to docker private registry"
          command: docker login  hub.phukethomevilla.com -u $PRIVATE_REGISTRY_USERNAME -p $PRIVATE_REGISTRY_PASSWORD
      - run:
          name: "Build image for production"
          command: docker build -t hub.phukethomevilla.com/docker-nextjs .
      - run:
          name: "Push image to docker private registry"
          command: docker push hub.phukethomevilla.com/docker-nextjs
      - run:
          name: "Pull image and start docker in production"
          command: |
            ssh -i ~/.ssh/id_rsa_circleci $DROPLET_USER@$DROPLET_IP './deploy_project.sh'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
