version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.14.0

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: yarn install
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn

    deploy-prod:
        docker:
            - image: circleci/node:12.14.0

        working_directory: ~/repo

        steps:
            - checkout

            - run:
                  name: install netlify cli
                  command: sudo npm install netlify-cli -g
            - run:
                  name: deploy site to netlify
                  command: netlify deploy --dir=/home/circleci/project/public -p

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy-prod:
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - build
